version: '3.8'
services:
  prom:
    image: prom/prometheus
    command:
      - --enable-feature=otlp-write-receiver
    network_mode: host # port 9090
    volumes:
      - ./prom.yml:/prometheus/prometheus.yml
