version: 1
disable_existing_loggers: false

root:
  handlers: [default]
  level: DEBUG

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

formatters:
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s %(name)s %(levelprefix)s %(message)s"
    use_colors: null
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
